### ISSUE TITLE
Not connecting to default servers

### ISSUE THREAD

**Issue by ivanovd** [project-ecc/electrum-ecc#11]
I am using ver. 4.0.3 of the Windows wallet and it seems that I cannot connect to any of the default servers:

![image](https://user-images.githubusercontent.com/4889583/102212125-5635e800-3edd-11eb-995b-a7ecfb836c24.png)

Any idea?

**Comment by HenryYoung42** [comment]
ElectrumX Server on eccserver1.ddns.net had crashed and no others are running. Restarting ...

**Comment by HenryYoung42** [comment]
Will post back here again when service is restored. Then I will look into adding a second independent server.

**Comment by HenryYoung42** [comment]
That should be back up again now. Apologies for the inconvenience !

**Comment by ivanovd** [comment]
Yup, it is back up again. Thank you for the fast turnaround.
