### ISSUE TITLE
Windows installer creates shortcut comtaining a path error

### ISSUE THREAD

**Issue by HenryYoung42** [project-ecc/electrum-ecc#5]
The installed executable is electrum-ecc-3.3.4.3-ecc-7-gf5243081.exe, whereas the installed shortcut references electrum-3.3.4.3-ecc-7-gf5243081.exe
![Electrum Error](https://user-images.githubusercontent.com/8385576/58197363-fdcc4380-7cc3-11e9-8770-5e92039acbc8.png)

**Comment by smogm** [comment]
Do you know in which file the exe file name is defined?

**Comment by HenryYoung42** [comment]
It's not defined in a file but in a shortcut so that is probably created by the installer script somewhere.

**Comment by smogm** [comment]
Looks like this line and following:

https://github.com/project-ecc/electrum-ecc/blob/fc4a2a78bcb34d8ff5c63f4d0c9ee6054b7723a8/contrib/build-wine/electrum.nsi#L123-L132

**Comment by smogm** [comment]
Should be fixed here:

https://github.com/project-ecc/electrum-ecc/blob/82803d41b874f05d305940c48ba557611900c35c/contrib/build-wine/electrum.nsi#L123-L132
