### ISSUE TITLE
Ecc electrum wallet for android doesn't connect to server

### ISSUE THREAD

**Issue by ovisleek** [project-ecc/electrum-ecc#6]
I need some help. I installed the electrum-ecc apk for android. Transferred my coins from coinexchange to the ecc electrum wallet. Checked the transaction on chainz.cryptoid.info and it confirmed but can't see it in account balance on wallet. It keeps showing offline. I checked the network and it says not connected

**Comment by smogm** [comment]
Issue seems to be related to the internet provider.
He can't even connect when running `telnet eccserver1.ddns.net 50002`.
The issue seems not to be app related.

**Comment by smogm** [comment]
Should be solved by 9575e56820eb9e5d72febe9a920b3b3f34ddd134
